'use client';

import { useState, useRef, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Loader2, AlertCircle, Gamepad2, Code, Eye, Download, Copy, Check } from 'lucide-react';
import { HaleyCoreGlyph } from '@/components/HaleyCoreGlyph';

interface PreviewElement {
  type: string;
  name: string;
  position: { x: number; y: number; z: number };
  size: { x: number; y: number; z: number };
  color: string;
  shape?: string;
}

interface PreviewConfig {
  elements: PreviewElement[];
  lighting?: string;
  environment?: string;
}

interface GenerateResult {
  lua_code: string;
  preview_config: PreviewConfig;
  elements_created: number;
}

export default function RobloxExpertPage() {
  const router = useRouter();
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GenerateResult | null>(null);
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');
  const [copied, setCopied] = useState(false);

  // Simple 2D preview renderer
  useEffect(() => {
    if (!result?.preview_config || !canvasRef.current) return;

    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Clear canvas
    ctx.fillStyle = '#1a1e22';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw grid
    ctx.strokeStyle = '#2a2e32';
    ctx.lineWidth = 1;
    for (let x = 0; x < canvas.width; x += 20) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, canvas.height);
      ctx.stroke();
    }
    for (let y = 0; y < canvas.height; y += 20) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(canvas.width, y);
      ctx.stroke();
    }

    // Draw elements (simple top-down view)
    const centerX = canvas.width / 2;
    const centerY = canvas.height / 2;
    const scale = 4;

    result.preview_config.elements.forEach((element) => {
      const x = centerX + element.position.x * scale;
      const y = centerY - element.position.z * scale; // Use z for top-down

      ctx.fillStyle = element.color || '#4a9eff';
      ctx.globalAlpha = 0.8;

      if (element.shape === 'Ball' || element.shape === 'Cylinder') {
        ctx.beginPath();
        ctx.arc(x, y, (element.size.x * scale) / 2, 0, Math.PI * 2);
        ctx.fill();
      } else {
        const width = element.size.x * scale;
        const height = element.size.z * scale;
        ctx.fillRect(x - width / 2, y - height / 2, width, height);
      }

      // Draw label
      ctx.globalAlpha = 1;
      ctx.fillStyle = '#fff';
      ctx.font = '10px monospace';
      ctx.textAlign = 'center';
      ctx.fillText(element.name, x, y + (element.size.z * scale) / 2 + 12);
    });

    ctx.globalAlpha = 1;
  }, [result]);

  const handleGenerate = async () => {
    if (!description.trim()) {
      setError('Please describe a scene first.');
      return;
    }

    setError(null);
    setLoading(true);
    setResult(null);

    try {
      const response = await fetch('/api/module/robloxexpert/execute', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          action: 'generate_scene',
          description: description,
        }),
      });

      if (!response.ok) {
        throw new Error(`Generation failed: ${response.statusText}`);
      }

      const data = await response.json();
      setResult(data);
      setActiveTab('preview');
    } catch (err) {
      console.error('[RobloxExpert] Error:', err);

      // Generate mock result for demo
      const mockResult: GenerateResult = {
        lua_code: `-- Scene: ${description}
-- Generated by Roblox Expert

local Workspace = game:GetService("Workspace")
local Lighting = game:GetService("Lighting")

-- Clear existing generated content
for _, child in pairs(Workspace:GetChildren()) do
    if child:GetAttribute("HaleyGenerated") then
        child:Destroy()
    end
end

-- Environment Setup
local floor = Instance.new("Part")
floor.Name = "Floor"
floor:SetAttribute("HaleyGenerated", true)
floor.Size = Vector3.new(50, 1, 50)
floor.Position = Vector3.new(0, -0.5, 0)
floor.Anchored = true
floor.BrickColor = BrickColor.new("Bright green")
floor.Material = Enum.Material.Grass
floor.Parent = Workspace

-- Main Character
local character = Instance.new("Model")
character.Name = "MainCharacter"
character:SetAttribute("HaleyGenerated", true)

local body = Instance.new("Part")
body.Name = "Body"
body.Size = Vector3.new(2, 3, 1)
body.Position = Vector3.new(0, 3.5, 0)
body.Anchored = true
body.BrickColor = BrickColor.new("Bright blue")
body.Material = Enum.Material.SmoothPlastic
body.Parent = character

local head = Instance.new("Part")
head.Name = "Head"
head.Size = Vector3.new(1.5, 1.5, 1.5)
head.Position = Vector3.new(0, 5.75, 0)
head.Anchored = true
head.BrickColor = BrickColor.new("Light orange")
head.Material = Enum.Material.SmoothPlastic
head.Parent = character

character.Parent = Workspace

-- Tree
local tree = Instance.new("Model")
tree.Name = "Tree"
tree:SetAttribute("HaleyGenerated", true)

local trunk = Instance.new("Part")
trunk.Name = "Trunk"
trunk.Size = Vector3.new(2, 8, 2)
trunk.Position = Vector3.new(10, 4, 5)
trunk.Anchored = true
trunk.BrickColor = BrickColor.new("Reddish brown")
trunk.Material = Enum.Material.Wood
trunk.Parent = tree

local leaves = Instance.new("Part")
leaves.Name = "Leaves"
leaves.Shape = Enum.PartType.Ball
leaves.Size = Vector3.new(8, 8, 8)
leaves.Position = Vector3.new(10, 10, 5)
leaves.Anchored = true
leaves.BrickColor = BrickColor.new("Dark green")
leaves.Material = Enum.Material.Grass
leaves.Parent = tree

tree.Parent = Workspace

print("Scene generated successfully!")`,
        preview_config: {
          elements: [
            { type: 'Part', name: 'Floor', position: { x: 0, y: -0.5, z: 0 }, size: { x: 50, y: 1, z: 50 }, color: '#4ade80' },
            { type: 'Part', name: 'Body', position: { x: 0, y: 3.5, z: 0 }, size: { x: 2, y: 3, z: 1 }, color: '#3b82f6' },
            { type: 'Part', name: 'Head', position: { x: 0, y: 5.75, z: 0 }, size: { x: 1.5, y: 1.5, z: 1.5 }, color: '#fdba74' },
            { type: 'Part', name: 'Trunk', position: { x: 10, y: 4, z: 5 }, size: { x: 2, y: 8, z: 2 }, color: '#92400e' },
            { type: 'Part', name: 'Leaves', position: { x: 10, y: 10, z: 5 }, size: { x: 8, y: 8, z: 8 }, color: '#166534', shape: 'Ball' },
          ],
          lighting: 'default',
          environment: 'forest',
        },
        elements_created: 5,
      };

      setResult(mockResult);
      setActiveTab('preview');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCode = async () => {
    if (!result?.lua_code) return;

    try {
      await navigator.clipboard.writeText(result.lua_code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleExport = () => {
    if (!result?.lua_code) return;

    const blob = new Blob([result.lua_code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'roblox_scene.lua';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleReset = () => {
    setDescription('');
    setResult(null);
    setError(null);
  };

  return (
    <div className="full-screen flex overflow-hidden">
      <div className="space-bg">
        <div className="stars" />
        {[...Array(3)].map((_, i) => (
          <div
            key={i}
            className="shooting-star"
            style={{
              top: `${Math.random() * 50}%`,
              right: `${Math.random() * 50}%`,
              animationDelay: `${Math.random() * 3}s`,
            }}
          />
        ))}
      </div>

      <div className="flex-1 flex flex-col relative z-10">
        {/* Header */}
        <div className="glass-strong border-b border-border p-4">
          <div className="max-w-6xl mx-auto flex items-center justify-between">
            <button
              onClick={() => router.push('/')}
              className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-panel-light transition-colors"
            >
              <ArrowLeft size={20} />
              <span className="text-sm font-medium">Back to Haley</span>
            </button>
            <div className="flex items-center gap-2">
              <HaleyCoreGlyph size={24} className="text-primary" />
              <span className="text-lg font-bold text-gradient">Haley</span>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-8">
          <div className="max-w-6xl mx-auto">
            {/* Title Section */}
            <div className="text-center mb-8">
              <div className="flex justify-center mb-4">
                <div className="p-4 rounded-2xl bg-primary/10 border border-primary/20">
                  <Gamepad2 size={48} className="text-primary" />
                </div>
              </div>
              <h1 className="text-3xl font-bold text-gradient mb-2">
                Roblox Expert
              </h1>
              <p className="text-secondary">
                Describe a scene, get Roblox Lua code and preview
              </p>
              <p className="text-xs text-secondary/60 mt-1">
                Built for kids - no coding required!
              </p>
            </div>

            {/* Error Display */}
            {error && (
              <div className="glass border border-red-500/30 bg-red-500/10 rounded-lg p-4 mb-6 flex items-start gap-3">
                <AlertCircle size={20} className="text-red-500 flex-shrink-0 mt-0.5" />
                <p className="text-sm text-red-400">{error}</p>
              </div>
            )}

            {/* Input Section */}
            {!result && (
              <div className="glass rounded-xl border border-border p-6">
                <div className="space-y-6">
                  <div>
                    <label className="block text-lg font-medium mb-3">
                      Describe your scene
                    </label>
                    <textarea
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      placeholder="Example: A forest with tall trees, a small pond, and a friendly dragon flying overhead..."
                      rows={6}
                      className="w-full px-4 py-3 rounded-lg bg-panel-dark border border-border focus:border-primary focus:outline-none transition-colors resize-none text-sm"
                    />
                    <p className="text-xs text-secondary mt-2">
                      Be descriptive! Mention characters, environments, colors, and actions you want to see.
                    </p>
                  </div>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                    <button
                      onClick={() => setDescription('A medieval castle with tall towers, a dragon guarding the entrance, and torches lighting the walls')}
                      className="px-3 py-2 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                    >
                      Castle & Dragon
                    </button>
                    <button
                      onClick={() => setDescription('A space station floating in the stars with robots walking around and glowing neon lights')}
                      className="px-3 py-2 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                    >
                      Space Station
                    </button>
                    <button
                      onClick={() => setDescription('A magical forest with colorful trees, sparkles floating in the air, and a friendly wizard')}
                      className="px-3 py-2 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                    >
                      Magic Forest
                    </button>
                    <button
                      onClick={() => setDescription('An underwater ocean scene with coral, fish swimming around, and a treasure chest on the sandy floor')}
                      className="px-3 py-2 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                    >
                      Underwater
                    </button>
                  </div>

                  <button
                    onClick={handleGenerate}
                    disabled={loading || !description.trim()}
                    className="w-full px-6 py-3 rounded-lg bg-primary/20 hover:bg-primary/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-sm font-medium text-primary flex items-center justify-center gap-2"
                  >
                    {loading ? (
                      <>
                        <Loader2 size={18} className="animate-spin" />
                        Generating Scene...
                      </>
                    ) : (
                      <>
                        <Gamepad2 size={18} />
                        Generate Scene
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}

            {/* Results Section */}
            {result && (
              <div className="space-y-6">
                {/* Stats Bar */}
                <div className="glass rounded-xl border border-border p-4 flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-green-400" />
                      <span className="text-sm">Scene Generated</span>
                    </div>
                    <span className="text-xs text-secondary">
                      {result.elements_created} elements created
                    </span>
                  </div>
                  <button
                    onClick={handleReset}
                    className="px-3 py-1.5 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                  >
                    New Scene
                  </button>
                </div>

                {/* Tab Buttons */}
                <div className="flex gap-2">
                  <button
                    onClick={() => setActiveTab('preview')}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-colors text-sm ${
                      activeTab === 'preview'
                        ? 'bg-primary/20 text-primary'
                        : 'bg-panel-light hover:bg-panel-medium'
                    }`}
                  >
                    <Eye size={16} />
                    Preview
                  </button>
                  <button
                    onClick={() => setActiveTab('code')}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-colors text-sm ${
                      activeTab === 'code'
                        ? 'bg-primary/20 text-primary'
                        : 'bg-panel-light hover:bg-panel-medium'
                    }`}
                  >
                    <Code size={16} />
                    Lua Code
                  </button>
                </div>

                {/* Preview Panel */}
                {activeTab === 'preview' && (
                  <div className="glass rounded-xl border border-border p-6">
                    <h3 className="text-lg font-semibold mb-4">Scene Preview (Top-Down View)</h3>
                    <div className="flex justify-center">
                      <canvas
                        ref={canvasRef}
                        width={600}
                        height={400}
                        className="rounded-lg border border-border"
                      />
                    </div>
                    <p className="text-xs text-secondary text-center mt-4">
                      This is a simplified preview. The actual scene will look much better in Roblox Studio!
                    </p>
                  </div>
                )}

                {/* Code Panel */}
                {activeTab === 'code' && (
                  <div className="glass rounded-xl border border-border overflow-hidden">
                    <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-panel-dark">
                      <span className="text-sm font-medium">Lua Code</span>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={handleCopyCode}
                          className="flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg bg-panel-light hover:bg-panel-medium transition-colors"
                        >
                          {copied ? <Check size={14} /> : <Copy size={14} />}
                          {copied ? 'Copied!' : 'Copy'}
                        </button>
                      </div>
                    </div>
                    <pre className="p-4 text-sm font-mono overflow-x-auto max-h-[500px] overflow-y-auto">
                      <code className="text-green-400">{result.lua_code}</code>
                    </pre>
                  </div>
                )}

                {/* Export Button */}
                <div className="flex gap-3">
                  <button
                    onClick={handleExport}
                    className="flex-1 px-6 py-3 rounded-lg bg-primary/20 hover:bg-primary/30 transition-colors text-sm font-medium text-primary flex items-center justify-center gap-2"
                  >
                    <Download size={18} />
                    Export to Studio (.lua)
                  </button>
                </div>

                {/* Instructions */}
                <div className="glass rounded-xl border border-border p-6">
                  <h3 className="text-lg font-semibold mb-3">How to use in Roblox Studio</h3>
                  <ol className="space-y-2 text-sm text-secondary">
                    <li className="flex items-start gap-2">
                      <span className="font-bold text-primary">1.</span>
                      Open Roblox Studio and create a new place (or open an existing one)
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="font-bold text-primary">2.</span>
                      Go to View → Command Bar (or press Ctrl+Shift+C)
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="font-bold text-primary">3.</span>
                      Copy the Lua code above and paste it into the Command Bar
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="font-bold text-primary">4.</span>
                      Press Enter to run the code and watch your scene appear!
                    </li>
                  </ol>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
